name = "Ledger"
grammar = "ledger"
path_suffixes = ["journal", "ledger", "ldg", "ldgr"]
# See https://www.ledger-cli.org/3.0/doc/ledger3.html#Commenting-on-your-Journal
line_comments = ["; ", "# ", "% ", "| ", "* "]
