id = "ledger"
name = "Ledger"
version = "0.1.0"
schema_version = 1
authors = ["Mark Stewart <me@markstewart.dev>"]
description = "Support for ledger journal files"
repository = "https://github.com/mrkstwrt/zed-ledger"

[grammars.ledger]
repository = "https://github.com/cbarrete/tree-sitter-ledger"
commit = "96c92d4908a836bf8f661166721c98439f8afb80"

[language_servers.ledger-language-server]
name = "ledger-language-server"
language = "Ledger"
language_ids = { Ledger = "ledger" }
